const GITHUB_API = "https://api.github.com";

function headers() {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error("GITHUB_TOKEN is not set");
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28",
  };
}

export async function createGitHubRepo(
  repoName: string
): Promise<{ repoUrl: string; cloneUrl: string; owner: string }> {
  const res = await fetch(`${GITHUB_API}/user/repos`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      name: repoName,
      description: "Prototype generated by Anvil",
      private: true,
      auto_init: false,
    }),
  });

  if (!res.ok) {
    const body = await res.text();
    // 422 = repo already exists — try with a timestamp suffix
    if (res.status === 422) {
      return createGitHubRepo(`${repoName}-${Date.now()}`);
    }
    throw new Error(`GitHub createRepo failed: ${body}`);
  }

  const repo = (await res.json()) as {
    html_url: string;
    clone_url: string;
    owner: { login: string };
  };

  return {
    repoUrl: repo.html_url,
    cloneUrl: repo.clone_url,
    owner: repo.owner.login,
  };
}

/**
 * Push multiple files to a GitHub repo in a single commit using the Git Data API.
 * Creates the initial commit on the default branch (main).
 */
export async function pushFilesToGitHub(
  owner: string,
  repo: string,
  files: Record<string, string>,
  message = "Initial prototype generated by Anvil"
): Promise<void> {
  const base = `${GITHUB_API}/repos/${owner}/${repo}`;

  // 1. Create blobs for all files
  const blobs = await Promise.all(
    Object.entries(files).map(async ([path, content]) => {
      const res = await fetch(`${base}/git/blobs`, {
        method: "POST",
        headers: headers(),
        body: JSON.stringify({
          content: Buffer.from(content).toString("base64"),
          encoding: "base64",
        }),
      });
      if (!res.ok) throw new Error(`blob failed for ${path}: ${await res.text()}`);
      const { sha } = (await res.json()) as { sha: string };
      return { path, sha };
    })
  );

  // 2. Create a tree with all blobs
  const treeRes = await fetch(`${base}/git/trees`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({
      tree: blobs.map(({ path, sha }) => ({
        path,
        mode: "100644",
        type: "blob",
        sha,
      })),
    }),
  });
  if (!treeRes.ok) throw new Error(`tree failed: ${await treeRes.text()}`);
  const { sha: treeSha } = (await treeRes.json()) as { sha: string };

  // 3. Create a commit (no parent = initial commit)
  const commitRes = await fetch(`${base}/git/commits`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({ message, tree: treeSha, parents: [] }),
  });
  if (!commitRes.ok) throw new Error(`commit failed: ${await commitRes.text()}`);
  const { sha: commitSha } = (await commitRes.json()) as { sha: string };

  // 4. Create the main branch ref
  const refRes = await fetch(`${base}/git/refs`, {
    method: "POST",
    headers: headers(),
    body: JSON.stringify({ ref: "refs/heads/main", sha: commitSha }),
  });
  if (!refRes.ok) throw new Error(`ref failed: ${await refRes.text()}`);
}
